### ISSUE TITLE
 favicon is not displayed

### ISSUE THREAD

**Issue by kosirm** [KurokuLabs/react-static-favicons#2]
Favicon on chrome is not displayed. If I look at the page source, there is no favicon metadata. I can see that icon is copied to dest folder if I build site, but it is not displayed.

**Comment by DisposaBoy** [comment]
How are you serving the site? `localhost:3000/...` by default, is the dev server; it doesn't show the static html produced by `yarn build` so it won't show any favicon.
You'll need to use `yarn serve`  or similar command or use a real web server to serve the contents in your `dist` folder.

**Comment by kosirm** [comment]
Thanks, yes I tried also on live site.
Anyway, build time jumped so much, that I added just simple favicon...
`<link rel="icon" type="image/png" href="http://mypage/logo.png" />`
